# Generated by Django 3.1.4 on 2021-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='user.UserGroup', verbose_name='속한 그룹'),
        ),
    ]
