# Generated by Django 3.1.4 on 2021-08-04 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='카테고리 이름을 입력하세요.', max_length=255, verbose_name='카테고리 이름')),
                ('mid', models.CharField(help_text='영문+숫자 조합만 가능한 카테고리의 고유값입니다.', max_length=255, unique=True, verbose_name='카테고리 고유값')),
                ('description', models.TextField(blank=True, help_text='카테고리에 대한 간단한 설명을 입력합니다.', null=True, verbose_name='카테고리 설명')),
                ('snapshot_image', models.ImageField(blank=True, help_text='해당하는 이미지 파일을 선택하세요.', null=True, upload_to='', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='명칭')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='anonymous user', max_length=32, verbose_name='닉네임')),
                ('profile_article', models.CharField(blank=True, max_length=512, null=True, verbose_name='프로필 정보')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('sex_choices', models.CharField(choices=[('MA', '남자'), ('FE', '여자')], default='MA', max_length=2)),
                ('categories', models.ManyToManyField(to='user.Categories', verbose_name='관심 카테고리')),
                ('groups', models.ManyToManyField(to='auth.Group', verbose_name='속한 그룹')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
