# Generated by Django 3.1.4 on 2021-09-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210908_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
