# Generated by Django 3.1.4 on 2021-08-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210816_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='phoneverifier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
    ]
