# Generated by Django 3.1.4 on 2021-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210804_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
        migrations.AddField(
            model_name='user',
            name='nickName',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='닉네임'),
        ),
    ]
