# Generated by Django 3.1.4 on 2021-08-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210818_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifier',
            name='created',
            field=models.DateTimeField(verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='phoneverifier',
            name='created',
            field=models.DateTimeField(verbose_name='생성일시'),
        ),
    ]
