# Generated by Django 3.1.4 on 2021-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='포인트'),
        ),
    ]
