# Generated by Django 3.1.4 on 2021-08-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210818_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': '소셜 카테고리', 'verbose_name_plural': '소셜 카테고리'},
        ),
    ]
