# Generated by Django 3.1.4 on 2021-08-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210805_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickName',
            new_name='name',
        ),
    ]
