# Generated by Django 3.1.4 on 2021-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210805_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(to='user.Categories', verbose_name='관심 카테고리'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_article',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='프로필 정보'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex_choices',
            field=models.CharField(choices=[('MA', '남자'), ('FE', '여자')], default='MA', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='user.UserGroup', verbose_name='속한 그룹'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
