# Generated by Django 3.1.4 on 2021-10-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershipping',
            name='big_address',
            field=models.CharField(max_length=2048, verbose_name='기본 주소'),
        ),
        migrations.AlterField(
            model_name='usershipping',
            name='small_address',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='상세 주소'),
        ),
    ]
