# Generated by Django 3.1.4 on 2021-10-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211013_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='요구사항')),
            ],
        ),
    ]
