# Generated by Django 3.1.4 on 2021-10-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_shippingrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrequest',
            options={'verbose_name': '배송 요청사항', 'verbose_name_plural': '배송 요청사항'},
        ),
        migrations.AlterModelOptions(
            name='usershipping',
            options={'verbose_name': '유저 배송지', 'verbose_name_plural': '유저 배송지'},
        ),
    ]
