# Generated by Django 3.1.4 on 2021-09-23 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(blank=True, help_text='상품 이름입니다.', max_length=512, null=True, verbose_name='상품 이름')),
                ('gift_url', models.URLField(verbose_name='상품 설명 url')),
                ('orderer_name', models.CharField(blank=True, help_text='주문자 이름입니다.', max_length=64, null=True, verbose_name='주문자 이름')),
                ('orderer_phone', models.CharField(blank=True, help_text='주문자 휴대폰 번호입니다.', max_length=32, null=True, verbose_name='주문자 휴대폰 번호')),
                ('gift_reason', models.TextField(blank=True, help_text='선물 사유가 들어갈 곳입니다.', null=True, verbose_name='선물 사유')),
                ('message', models.TextField(blank=True, help_text='전달 메세지가 들어갈 곳입니다.', null=True, verbose_name='전달하고싶은 메세지')),
                ('letter', models.TextField(blank=True, help_text='위 내용을 종합하셔서 편지로 만들어주세요.', null=True, verbose_name='종합 편지')),
                ('letter_deliver', models.BooleanField(default=False, help_text='편지 전달 완료 시 True로 바뀝닏나.', verbose_name='선물 전달 여부')),
                ('order_date', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 16, 1, 11, 615484), help_text='주문 날짜입니다.', verbose_name='주문 날짜')),
                ('reciever_name', models.CharField(blank=True, help_text='선물 수령인입니다.', max_length=64, null=True, verbose_name='선물 수령인')),
                ('reciever_phone', models.CharField(blank=True, help_text='선물 수령인 휴대폰 번호입니다.', max_length=64, null=True, verbose_name='선물 수령인 휴대폰 번호')),
                ('recieve_date', models.DateTimeField(default=datetime.datetime(2021, 9, 30, 16, 1, 11, 615519), verbose_name='배송지 입력 기간')),
                ('reciever_big_address', models.TextField(blank=True, help_text='선물 수령인 배송지입니다.', null=True, verbose_name='수령인 주소')),
                ('reciever_small_address', models.TextField(blank=True, help_text='선물 수령인 상세 배송지입니다.', null=True, verbose_name='수령인 상세 주소')),
                ('reciever_requirements', models.TextField(blank=True, help_text='선물 수령인 요청사항 입니다.', null=True, verbose_name='수령인 요청사항')),
            ],
        ),
    ]
