# Generated by Django 3.1.4 on 2021-10-07 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 18, 59, 16, 55474), help_text='주문 날짜입니다.', verbose_name='주문 날짜'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recieve_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 18, 59, 16, 55514), verbose_name='배송지 입력 기간'),
        ),
    ]
