# Generated by Django 3.1.4 on 2021-07-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '채팅',
                'verbose_name_plural': '채팅',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='텍스트')),
                ('image', models.URLField(blank=True, null=True, verbose_name='이미지')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='채팅')),
            ],
            options={
                'verbose_name': '메세지',
                'verbose_name_plural': '메세지',
                'ordering': ['-created'],
            },
        ),
    ]
