# Generated by Django 3.1.4 on 2020-12-14 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user_set', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='참여자')),
            ],
            options={
                'verbose_name': '채팅',
                'verbose_name_plural': '채팅',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('S', '발신자'), ('R', '수신자')], max_length=1, verbose_name='발신자 타입')),
                ('text', models.TextField(verbose_name='텍스트')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='채팅')),
            ],
            options={
                'verbose_name': '메세지',
                'verbose_name_plural': '메세지',
                'ordering': ['-created'],
            },
        ),
    ]
