# Generated by Django 3.1.4 on 2020-12-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_type',
        ),
    ]
