# Generated by Django 3.1.4 on 2021-08-21 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceBigCategories',
            fields=[
                ('title', models.CharField(help_text='메인 카테고리 이름을 입력하세요.', max_length=255, verbose_name='메인 카테고리 이름')),
                ('mid', models.CharField(help_text='영문+숫자 조합만 가능한 카테고리의 고유값입니다.', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='메인 카테고리 고유값')),
                ('description', models.TextField(blank=True, help_text='메인 카테고리에 대한 간단한 설명을 입력합니다.', null=True, verbose_name='카테고리 설명')),
                ('snapshot_image', models.ImageField(blank=True, help_text='해당하는 이미지 파일을 선택하세요.', null=True, upload_to='', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '메인 카테고리',
                'verbose_name_plural': '메인 카테고리',
            },
        ),
        migrations.CreateModel(
            name='CommerceSmallCategories',
            fields=[
                ('title', models.CharField(help_text='세부 카테고리 이름을 입력하세요.', max_length=255, verbose_name='세부 카테고리 이름')),
                ('mid', models.CharField(help_text='영문+숫자 조합만 가능한 카테고리의 고유값입니다.', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='카테고리 고유값')),
                ('description', models.TextField(blank=True, help_text='세부 카테고리에 대한 간단한 설명을 입력합니다.', null=True, verbose_name='카테고리 설명')),
                ('snapshot_image', models.ImageField(blank=True, help_text='해당하는 이미지 파일을 선택하세요.', null=True, upload_to='', verbose_name='이미지')),
                ('big_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.commercebigcategories', verbose_name='메인 카테고리')),
            ],
            options={
                'verbose_name': '세부 카테고리',
                'verbose_name_plural': '세부 카테고리',
            },
        ),
    ]
