<<<<<<< HEAD:api/magazine/migrations/0002_auto_20210813_1800.py
# Generated by Django 3.1.4 on 2021-08-13 18:00
=======
# Generated by Django 3.1.4 on 2021-08-12 18:24
>>>>>>> 9b11bc955ad84a03386a87baaaa13132ef76e47b:api/magazine/migrations/0002_auto_20210812_1824.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:api/magazine/migrations/0002_auto_20210813_1800.py
        ('magazine', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('magazine', '0001_initial'),
>>>>>>> 9b11bc955ad84a03386a87baaaa13132ef76e47b:api/magazine/migrations/0002_auto_20210812_1824.py
    ]

    operations = [
        migrations.AddField(
            model_name='summernote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='글쓴이'),
        ),
        migrations.AddField(
            model_name='magazines',
            name='categories',
            field=models.ManyToManyField(related_name='magazines', to='user.Categories', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='magazines',
            name='like_users',
            field=models.ManyToManyField(related_name='like_magazines', to=settings.AUTH_USER_MODEL, verbose_name='이 매거진을 좋아한 사람들'),
        ),
        migrations.AddField(
            model_name='magazines',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성'),
        ),
        migrations.AddField(
            model_name='magazinecomments',
            name='magazines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_comments', to='magazine.magazines', verbose_name='매거진'),
        ),
        migrations.AddField(
            model_name='magazinecomments',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.magazinecomments', verbose_name='대댓글'),
        ),
        migrations.AddField(
            model_name='magazinecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='files',
            name='magazines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.magazines', verbose_name='매거진'),
        ),
    ]
