# Generated by Django 3.1.4 on 2021-08-13 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0002_auto_20210812_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazines',
            name='scrapped_users',
            field=models.ManyToManyField(related_name='scrapped_magazines', to=settings.AUTH_USER_MODEL, verbose_name='이 매거진을 스크랩한 사람들'),
        ),
    ]
