# Generated by Django 3.2.8 on 2021-10-28 17:45

import api.magazine.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=functools.partial(api.magazine.models._update_filename, *(), **{'path': 'image/%Y/%m/%d/'}), verbose_name='배너 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.TextField(default='카탈로그 설명입니다.', verbose_name='카탈로그 설명')),
                ('collection', models.CharField(blank=True, help_text='클레이풀 상의 콜렉션에 해당하는 ID를 입력해주세요.', max_length=255, null=True, verbose_name='콜렉션 ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성')),
            ],
        ),
    ]
