# Generated by Django 3.1.4 on 2021-08-11 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20210807_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinecomments',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magazine.magazinecomments'),
        ),
        migrations.AlterField(
            model_name='magazinecomments',
            name='magazines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazine_comments', to='magazine.magazines', verbose_name='매거진'),
        ),
    ]
