# Generated by Django 3.1.4 on 2021-08-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20210811_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinecomments',
            name='ipaddress',
        ),
    ]
