# Generated by Django 3.2.8 on 2021-10-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': '카탈로그', 'verbose_name_plural': '카탈로그'},
        ),
    ]
