# Generated by Django 3.1.4 on 2021-08-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_remove_magazinecomments_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazines',
            name='ipaddress',
        ),
        migrations.RemoveField(
            model_name='summernote',
            name='ipaddress',
        ),
    ]
