# Generated by Django 3.1.4 on 2021-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20210825_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazines',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='브랜드 이름'),
        ),
    ]
