# Generated by Django 3.1.4 on 2021-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_auto_20210906_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazines',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='magazines',
            name='products',
        ),
        migrations.AddField(
            model_name='magazines',
            name='collection',
            field=models.CharField(blank=True, help_text='클레이풀 상의 콜렉션에 해당하는 ID를 입력해주세요.', max_length=255, null=True, verbose_name='콜렉션 ID'),
        ),
    ]
