# Generated by Django 3.1.4 on 2021-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_magazines_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='brand',
            field=models.CharField(blank=True, help_text='클레이풀 상의 브랜드에 해당하는 ID를 입력해주세요.', max_length=64, null=True, verbose_name='콜렉션 ID'),
        ),
    ]
