# Generated by Django 3.1.4 on 2021-09-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_auto_20210906_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazines',
            name='brand',
        ),
    ]
