# Generated by Django 3.1.4 on 2021-10-19 17:56

import api.magazine.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_magazines_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazines',
            name='is_banner',
            field=models.BooleanField(default=False, help_text='체크 하시면 어플리케이션 메인 배너에 등록 됩니다.', verbose_name='메인 배너 노출 여부'),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='banner_image',
            field=models.ImageField(default=3, upload_to=functools.partial(api.magazine.models._update_filename, *(), **{'path': 'image/%Y/%m/%d/'}), verbose_name='배너 이미지'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magazines',
            name='is_main',
            field=models.BooleanField(default=False, help_text='체크 하시면 어플리케이션 메인 매거진에 등록 됩니다.', verbose_name='메인 매거진 노출 여부'),
        ),
    ]
