# Generated by Django 3.1.4 on 2021-10-19 18:00

import api.magazine.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0012_auto_20211019_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(api.magazine.models._update_filename, *(), **{'path': 'image/%Y/%m/%d/'}), verbose_name='배너 이미지'),
        ),
    ]
