# Generated by Django 3.1.4 on 2021-10-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0013_auto_20211019_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazines',
            name='subtitle',
            field=models.CharField(default='부제목입니다.', max_length=1024, verbose_name='부제목'),
        ),
    ]
