# Generated by Django 3.1.4 on 2021-10-18 13:41

import api.magazine.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('banner_image', models.ImageField(upload_to=functools.partial(api.magazine.models._update_filename, *(), **{'path': 'catalog/image/%Y/%m/%d/'}), verbose_name='배너 이미지')),
                ('collection', models.CharField(help_text='클레이풀 상의 콜렉션에 해당하는 ID를 입력해주세요.', max_length=255, verbose_name='콜렉션 ID')),
                ('choices', models.CharField(choices=[('MA', '남자'), ('FE', '여자'), ('BE', '뷰')], default='FE', max_length=2, verbose_name='선택')),
            ],
            options={
                'verbose_name': '카탈로그',
                'verbose_name_plural': '카탈로그',
            },
        ),
    ]
