# Generated by Django 3.1.4 on 2021-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='choices',
            field=models.CharField(choices=[('맨', 'Male'), ('우먼', 'Female'), ('뷰티', 'Beauty')], default='우먼', max_length=32, verbose_name='선택'),
        ),
    ]
