# Generated by Django 3.1.4 on 2021-10-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_pointlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointLog',
        ),
    ]
